### PR TITLE
Add 'required' Attribute to Name Field

### PR DESCRIPTION
**Pull request by gkatrakazas**
Added the 'required' attribute to the 'name' input field in the signup form to make it mandatory for users to provide their name before submitting the form.

### CODE REVIEW

**Review by emlun — COMMENTED** [review]
I think it would be cleaner to extract a component prop like this, don't you think?
https://github.com/wwWallet/wallet-frontend/compare/fix/empty-nickname-signup...forminputfield-required?expand=1

**Comment by gkatrakazas** [comment]
Maybe we could add a maximum character limit for the name?

**Comment by emlun** [comment]
Hm, yeah, that's probably a good idea. Authenticators are allowed to silently truncate the name to 64 bytes (see [`PublicKeyCredentialEntity.name`](https://w3c.github.io/webauthn/#dom-publickeycredentialentity-name) and [`PublicKeyCredentialUserEntity.displayName`](https://w3c.github.io/webauthn/#dom-publickeycredentialuserentity-displayname)), so a max limit is probably good to prevent confusion.

Note, though, that the relevant limit here is bytes, not characters. These strings are UTF-8 encoded, so for example Greek and Cyrillic take 2 bytes per character, and emoji and some Asian characters take 4 bytes (Asian scripts may be less important for an EU system, but still). So we might need to use `TextEncoder` to measure the length in bytes instead of relying on the `maxlength` attribute, since [`maxlength` only counts UTF-16 code units](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#maxlength).

**Comment by emlun** [comment]
See also: https://github.com/w3c/webauthn/issues/1994

**Comment by gkatrakazas** [comment]
That's a good idea! Also We can accept only number and letters in the input, excluding special characters. What do you think?

**Comment by emlun** [comment]
We could, but I don't really see any reason to set that restriction. The name isn't used for any application logic, just to be displayed back to the user, so there's no particular reason to enforce a particular format. And I don't think it seems fair to prevent users with Greek and Cyrillic names from using their native script, so it doesn't seem reasonable to restrict the character set just for the sake of making `maxlength` agree with UTF-8 byte length.

**Comment by gkatrakazas** [comment]
That's true, there is no critical reason for this restriction, so we proceed as you said before. Also feel free to make any updates-commits in this branch. Of course.

**Comment by emlun** [comment]
I think this PR is good to merge, and we can follow up about the max length warning/limit later. :slightly_smiling_face:

**Review by emlun — APPROVED** [review]

**Pull request merged**
