### PR TITLE
Passing user data on password unlocking

### PR DESCRIPTION
**Pull request by kkmanos**

### CODE REVIEW

**Review by emlun — APPROVED** [review]

**Comment by kkmanos** [comment]
The initial commit seems to be creating cached users. Instead, I am now setting only the userHandleB64u

**Comment by emlun** [comment]
Was that not the intent? What else is the motivation for this?

**Comment by kkmanos** [comment]
I noticed that the userHandle is not stored in the session storage when logged-in or signed-up with username/password, making it inaccessible through the keystore.

Instead of this PR, do you think that it would be better to fetch the user's info (including the userHandle) through the `/user/session/account-info` endpoint?

**Comment by emlun** [comment]
Ah, I see. So the problem was that the user would show up as a "Log in as..." button, but the user has no passkeys so clicking that button always fails? I think we can fix that with a simple filter in the `cachedUsers` updater effect.

For the other part, I think it might be best to just expose the `setUserHandleB64u` function in the `LocalStorageKeystore` API. Calling `keystore.initPassword` twice is dangerous because it'll re-initialize the keystore with a new wallet in the local copy of the `privateData`, overwriting the wallet that was sent to the server, so there's an immediate desync between local and server state.

Shall I open another PR showing what I mean?

**Comment by kkmanos** [comment]
If you think that exposing setUserHandleB64u will be useful in other cases as well in the future, then you can proceed with opening a PR for it. Otherwise, I think that we can avoid it for know.

What I am thinking is that I should close this PR and instead solve the issue of the initial use-case I had in mind by accessing the account info.

What is your opinion?

**Comment by kkmanos** [comment]
Closing this PR because the alternative PR https://github.com/wwWallet/wallet-frontend/pull/300 is prefered

**Pull request closed without merging**
